### PR TITLE
Ignore /*.lock files

### PR DESCRIPTION
**Pull request by sspreitzer**

### CODE REVIEW

**Comment by sspreitzer** [comment]
Who needs lock files in git? :-)

**Comment by solarkennedy** [comment]
Well, depending on which rubyist you ask, Gemfile.lock files should be committed because they represent a snapshot of all the dependencies and allows reproducible builds.

Granted, this is a puppet module and we blow away gemfile.lock anyway at travis time.

**Comment by solarkennedy** [comment]
Looks like puppetlabs does this on all their modules too: 
https://github.com/puppetlabs/modulesync_configs/blob/bac142b47f8a6871eef3ee2ca03d666012d0e9f9/moduleroot/.gitignore#L3

**Comment by sspreitzer** [comment]
Ah nice, thank you!

**Pull request merged**
