### PR TITLE
Ensure `validate_re` calls are wrapped in `if` checks to avoid passing undef

### PR DESCRIPTION
**Pull request by jearls**

### CODE REVIEW

**Comment by jearls** [comment]
Fixes #181

**Comment by solarkennedy** [comment]
This means we no longer get protection from things like users accidentally putting in: `enable_sdb => false`, because it will be false in the if block and skip the validation. (right?)

**Comment by jearls** [comment]
reworked to specifically check for `undef`.  better?

**Comment by solarkennedy** [comment]
Looks great! Thank you.

**Pull request merged**
