### PR TITLE
Empty Zone Generation control

### PR DESCRIPTION
**Pull request by evidex**
Performing a bit of necromancy to resurrect #69 and implement validation & a parameter doc.

### CODE REVIEW

**Comment by evidex** [comment]
Again, I suspect failing builds are due to Issue #142

**Comment by evidex** [comment]
Anything I can do to help this get merged?

**Comment by solarkennedy** [comment]
Merged!

**Comment by solarkennedy** [comment]
Thanks!

**Comment by evidex** [comment]
Awesome, thanks!

**Pull request merged**
